language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
script: bash travisScript.bash
branches:
  except:
  - travis-ci
env:
  global:
  - secure: VuqdwfWVV+uBOOfz1NJ75lvpPtH61JeQ7MAw6nvxhMK3shAxcIKYmq7tZdXpv6YSg4FALTnydxXznJe5uNGpma4Gy98xxc38YKp8sumNsydsI5d/PlfkvZOWDD3LyZxUApKkWa5h6da9sD+FISgg7ITU1O7fpVIj8x197OmVlXs=
